apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-cloud-serverless
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: spring-cloud-serverless
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
      - name: BP_NATIVE_IMAGE
        value: "true"
      - name: BP_MAVEN_BUILD_ARGUMENTS
        value: "-Pnative -Dmaven.test.skip=true --no-transfer-progress package"
  params:
    - name: clusterBuilder
      value: default
  source:
    git:
      url: https://github.com/vudayani-vmw/spring-cloud-serverless
      ref:
        branch: main
